# Generated by Django 5.1.15 on 2026-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('stadium', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('total_seats', models.PositiveIntegerField(default=200)),
                ('available_seats', models.PositiveIntegerField(default=200)),
                ('vip_price', models.PositiveIntegerField(default=15000)),
                ('regular_price', models.PositiveIntegerField(default=5000)),
            ],
        ),
    ]
